"""add banks table

Revision ID: 4ea00da4876d
Revises: cef2847ac4c5
Create Date: 2021-11-29 08:42:28.417622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ea00da4876d'
down_revision = 'cef2847ac4c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('banks',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('agency', sa.String(), nullable=False),
    sa.Column('account', sa.String(), nullable=False),
    sa.Column('bank_code', sa.String(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer_manager.customers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='customer_manager'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('banks', schema='customer_manager')
    # ### end Alembic commands ###
