default:
  log_config_path: config/logging.yml
  log_level: INFO

  app:
    title: Customers Manager

  database:
    uri: postgresql://customer_manager_adm:customer_manager_adm@localhost:5439/db_customer_manager
    schema: customer_manager

